### ISSUE TITLE
Error while running HCP_Data_Vis.py of 2-visualization-3d Jupyter notebook

### ISSUE THREAD

**Issue by pcdslab** [multinetlab-amsterdam/network_TDA_tutorial#2]
I got the following error while running HCP_Data_Vis.py of 2-visualization-3d Jupyter notebook, on my macbook with macOS High Sierra 10.13.6

3. Creating 3D visualisations with Plotly
First, we need to import the necessary backup script. Then, it is possible to use a list of values for most of the nodal metrics, e.g., centralities, etc.
 
%run "/Users/oswaldoartiles/networkTDA/network_TDA_tutorial/Background Scripts/HCP_Data_Vis.py"
------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/networkTDA/network_TDA_tutorial/Background Scripts/HCP_Data_Vis.py in <module>
   1397 
   1398 ## Create gray shell
-> 1399 brain_mesh =  meshio.read(path_brainobj) # Reading a brain.obj file
   1400 brain_trace = shell_brain(brain_mesh)
   1401 trace1, _, _, _ = dictpos(areas, path_pos) # Transparent shell

~/anaconda3/lib/python3.7/site-packages/meshio/_helpers.py in read(filename, file_format)
     67         raise ReadError(msg)
     68 
---> 69     return reader_map[file_format](filename)
     70 
     71 

~/anaconda3/lib/python3.7/site-packages/meshio/obj/_obj.py in read(filename)
     17 def read(filename):
     18     with open_file(filename, "r") as f:
---> 19         mesh = read_buffer(f)
     20     return mesh
     21 

~/anaconda3/lib/python3.7/site-packages/meshio/obj/_obj.py in read_buffer(f)
     91             )
     92 
---> 93     return Mesh(points, cells, point_data=point_data)
     94 
     95 

~/anaconda3/lib/python3.7/site-packages/meshio/_mesh.py in __init__(self, points, cells, point_data, cell_data, field_data, point_sets, cell_sets, gmsh_periodic, info)
     60             if len(self.point_data[key]) != len(self.points):
     61                 raise ValueError(
---> 62                     f"len(points) = {len(points)}, "
     63                     f'but len(point_data["{key}"]) = {len(point_data[key])}'
     64                 )

ValueError: len(points) = 54284, but len(point_data["obj:vn"]) = 48585

**Comment by fnobregasantos** [comment]
Dear Saeed,

Many thanks for the interest in using our Jupyter notebook for 3d visualisations. 

From your error message, it seems that your mesh object is incompatible (brain shell) with the dimensions required by the meshio package. 

I would then suggest to:
I) If you use a different brain shell than the one we provide in the notebook, check for compatibility in format for your 3d shell object brain.obj.
I) If you are using the same brain shell as ours,  verify if you are using the version of the meshio package compatible with our requirements.txt file, as well as other packages.

I hope that it helps. 

Best regards,

Fernando Santos

**Comment by fnobregasantos** [comment]
Yet,

Please notice that the meshio package had an update recently on 04/06:

https://pypi.org/project/meshio/

**Comment by OswArti** [comment]
I am Oswaldo Artiles, a PhD student in the Saeed Lab, who opened this issue. We are using everything provided in the notebook, but the meshio version installed in our anaconda is meshio 4.4.6, not the required 4.016 version. Do you think that there may be some incompatibility between your package and this meshio version? By the way, the 1-network analysis notebook is working ok. Your package is extremely useful for our research in network neuroscience. Thanks

**Comment by eduardacenteno** [comment]
Hey @OswArti , we are happy to know that the tutorial has been so useful!
About the issue, it's very likely that the package version is causing the bug. It's common for packages to be updated and end up crashing/causing bugs in codes. I'd suggest creating an environment in your anaconda and installing our dependencies as suggested in the readme (requirements.txt), or if you can't for now, running the notebooks in Binder. 
Best.

**Comment by multinetlab** [comment]
@pcdslab hey! We would like to ask if the issue was solved... If so, we'll close it :)

**Comment by OswArti** [comment]
Your recommendation might be a solution, but it takes time due to packages incompatibility. I suggest to update the requirements of your library or make them more flexible so that it can adapt easily to the new versions of the required packages. Thank you for your support. You may close the issue now.
