### ISSUE TITLE
installation issues

### ISSUE THREAD

**Issue by XinQi7788** [multinetlab-amsterdam/network_TDA_tutorial#5]
**Describe the bug**
Use the requirements.txt from the GitHub, inside the anaconda environment with python version 3.10.9, during the installation,  encountered many "subprocess-exited-with-error" during pip install -r requirements.txt. 

So I created a new requirements.txt file only use the libraries list in the suggested requirements inside the README file as below.
But still encountered the same installation errors. 
numpy==1.18.5
matplotlib==3.3.2
meshio==4.0.16
seaborn==0.11.0
pandas==1.1.3
networkx==2.4
nxviz==0.6.2
community==0.13
gudhi==3.4.1
plotly==4.6.0
scikit-learn==0.24.1
scipy==1.5.0
jupyterlab==1.2.0

**Screenshots**
![image](https://user-images.githubusercontent.com/77089761/223497303-d0d3e8a9-83f7-4096-8987-c76207f2ef83.png)

**Desktop (please complete the following information):**
system: 
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal

Please help me on the installation issues and looking forward to your reply. Thank you very much.

Xin

**Comment by eduardacenteno** [comment]
Hey Xin,
thanks for your message! Could you try creating an environment with Python 3.7 and testing the installation again, please?

**Comment by raphaelcuhk** [comment]
Hi, I faced the same problem as you. The solution is what @eduardacenteno said. The higher version of python3.7 would have several problems when loading package. You could remove your python package and download python 3.7.x depending on your system. Then entering the pip install requirement.txt again.
